version: '3'
services:
#  app:
#    container_name: app-thinko
#    image: app-thinko
#    build: ./
#    ports:
#      - "8080:8080"
#    depends_on:
#        - thinko-db
  thinko-db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thinko
    volumes:
      - ./src/main/resources/db/:/docker-entrypoint-initdb.d/
  pgadmin:
    image: dpage/pgadmin4:4.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./src/main/resources/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "15432:80"
    links:
      - "thinko-db:localhost"